// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5E-Tcr_LbwOc4Jey3GM0uz6QKU32vD9U',
    appId: '1:286185096600:web:050df2ebb6a83bc15c17ed',
    messagingSenderId: '286185096600',
    projectId: 'easykey-23a1e',
    authDomain: 'easykey-23a1e.firebaseapp.com',
    storageBucket: 'easykey-23a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfycuflI1V4clm8FhtWFXtXkMyqn2lU-8',
    appId: '1:286185096600:android:94b65fa931b3a4d35c17ed',
    messagingSenderId: '286185096600',
    projectId: 'easykey-23a1e',
    storageBucket: 'easykey-23a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcxcxa1jny3gzP0yd-uPjegUM9u7Fi_vo',
    appId: '1:286185096600:ios:04a06a87fef8046b5c17ed',
    messagingSenderId: '286185096600',
    projectId: 'easykey-23a1e',
    storageBucket: 'easykey-23a1e.appspot.com',
    iosBundleId: 'com.example.easykey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcxcxa1jny3gzP0yd-uPjegUM9u7Fi_vo',
    appId: '1:286185096600:ios:c5e993c0f86a6bce5c17ed',
    messagingSenderId: '286185096600',
    projectId: 'easykey-23a1e',
    storageBucket: 'easykey-23a1e.appspot.com',
    iosBundleId: 'com.example.easykey.RunnerTests',
  );
}
